---
# Clean up releases
- name: ANSISTRANO | Clean up code releases
  shell: ls -1dt {{ ansistrano_releases_path }}/* | tail -n +{{ ansistrano_keep_releases | int + 1 }} | xargs rm -rf
  when: ansistrano_keep_releases | int > 0

- name: ANSISTRANO | Clean up hook releases
  shell: ls -1dt {{ ansistrano_hooks_path }}/* | tail -n +{{ ansistrano_keep_releases | int + 1 }} | xargs rm -rf
  when: ansistrano_keep_releases | int > 0
