---
- name: ANSISTRANO | Ensure hooks folder exists
  file:
    state: directory
    path: "{{ ansistrano_hooks_path }}"

- name: ANSISTRANO | Get hooks path
  command: echo "{{ ansistrano_hooks_path }}/{{ ansistrano_release_version }}/deploy"
  register: ansistrano_hook_path

# Update hook deployment step
- include_tasks: "update-hook/download_unarchive.yml"
