---
- include_tasks: initial.yml

- include_tasks: update-hook.yml
  when: ansistrano_hook_get_url is defined

- include_tasks: register-hook-file.yml
  when: ansistrano_hook_get_url is defined

- include_tasks: "{{ ansistrano_before_setup_tasks_file | default('empty.yml') }}"
- include_tasks: setup.yml
- include_tasks: "{{ ansistrano_after_setup_tasks_file | default('empty.yml') }}"

- include_tasks: "{{ ansistrano_before_symlink_tasks_file | default('empty.yml') }}"
- include_tasks: symlink.yml
- include_tasks: "{{ ansistrano_after_symlink_tasks_file | default('empty.yml') }}"

- include_tasks: "{{ ansistrano_before_cleanup_tasks_file | default('empty.yml') }}"
- include_tasks: cleanup.yml
- include_tasks: "{{ ansistrano_after_cleanup_tasks_file | default('empty.yml') }}"

- include_tasks: update-supervisor.yml
