---
# setup
- stat:
    path: "{{ ansistrano_hook_path.stdout }}/rollback/before_setup_tasks.yml"
  register: st
- name: ANSISTRANO | Set before setup tasks file
  set_fact:
    ansistrano_before_setup_tasks_file: "{{ ansistrano_hook_path.stdout }}/rollback/before_setup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

- stat:
    path: "{{ ansistrano_hook_path.stdout }}/rollback/after_setup_tasks.yml"
  register: st
- name: ANSISTRANO | Set after setup tasks file
  set_fact:
    ansistrano_after_setup_tasks_file: "{{ ansistrano_hook_path.stdout }}/rollback/after_setup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

# symlink
- stat:
    path: "{{ ansistrano_hook_path.stdout }}/rollback/before_symlink_tasks.yml"
  register: st
- name: ANSISTRANO | Set before symlink tasks file
  set_fact:
    ansistrano_before_symlink_tasks_file: "{{ ansistrano_hook_path.stdout }}/rollback/before_symlink_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

- stat:
    path: "{{ ansistrano_hook_path.stdout }}/rollback/after_symlink_tasks.yml"
  register: st
- name: ANSISTRANO | Set after symlink tasks file
  set_fact:
    ansistrano_after_symlink_tasks_file: "{{ ansistrano_hook_path.stdout }}/rollback/after_symlink_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

# symlink cleanup
- stat:
    path: "{{ ansistrano_hook_path.stdout }}/rollback/before_cleanup_tasks.yml"
  register: st
- name: ANSISTRANO | Set before cleanup tasks file
  set_fact:
    ansistrano_before_cleanup_tasks_file: "{{ ansistrano_hook_path.stdout }}/rollback/before_cleanup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

- stat:
    path: "{{ ansistrano_hook_path.stdout }}/rollback/after_cleanup_tasks.yml"
  register: st
- name: ANSISTRANO | Set after cleanup tasks file
  set_fact:
    ansistrano_after_cleanup_tasks_file: "{{ ansistrano_hook_path.stdout }}/rollback/after_cleanup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists
