---
# setup
- stat:
    path: "{{ ansistrano_hook_path.stdout }}/before_setup.sh"
  register: st
- name: ANSISTRANO | Set before setup tasks file
  set_fact:
    ansistrano_before_setup_tasks_file: "hook-tasks/before_setup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

- stat:
    path: "{{ ansistrano_hook_path.stdout }}/after_setup.sh"
  register: st
- name: ANSISTRANO | Set after setup tasks file
  set_fact:
    ansistrano_after_setup_tasks_file: "hook-tasks/after_setup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

# symlink
- stat:
    path: "{{ ansistrano_hook_path.stdout }}/before_symlink.sh"
  register: st
- name: ANSISTRANO | Set before symlink tasks file
  set_fact:
    ansistrano_before_symlink_tasks_file: "hook-tasks/before_symlink_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

- stat:
    path: "{{ ansistrano_hook_path.stdout }}/after_symlink.sh"
  register: st
- name: ANSISTRANO | Set after symlink tasks file
  set_fact:
    ansistrano_after_symlink_tasks_file: "hook-tasks/after_symlink_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

# symlink cleanup
- stat:
    path: "{{ ansistrano_hook_path.stdout }}/before_cleanup.sh"
  register: st
- name: ANSISTRANO | Set before cleanup tasks file
  set_fact:
    ansistrano_before_cleanup_tasks_file: "hook-tasks/before_cleanup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists

- stat:
    path: "{{ ansistrano_hook_path.stdout }}/after_cleanup.sh"
  register: st
- name: ANSISTRANO | Set after cleanup tasks file
  set_fact:
    ansistrano_after_cleanup_tasks_file: "hook-tasks/after_cleanup_tasks.yml"
  when: st.stat.exists is defined and st.stat.exists
