---
# Path where the code must be deployed to
ansistrano_deploy_to: "/var/www/my-app"

# Folder name for the releases
ansistrano_version_dir: "releases"

# Softlink name for the current release
ansistrano_current_dir: "current"

# Full path to the hooks path folder
ansistrano_hooks_path: "{{ ansistrano_deploy_to }}/hooks"

# Remove rolled back release?
ansistrano_remove_rolled_back: yes

# Rollback to this release version (previous by default)
ansistrano_rollback_to_release: ""

# Sends anonymous stats to the www.ansistrano.com servers
# You can disallow it by just setting this parameter to "no" in your playbook
ansistrano_allow_anonymous_stats: yes

ansistrano_unarchive_owner: "default"
ansistrano_unarchive_group: "default"
