---
# We should be able to remove default(omit) filters and add defaults once we deprecate Ansible 1.9
- name: ANSISTRANO | download | Download code
  get_url:
    url: "{{ ansistrano_get_url }}"
    dest: "{{ ansistrano_release_path.stdout }}/{{ ansistrano_get_url | basename }}"
    force_basic_auth: "{{ ansistrano_download_force_basic_auth | default(omit) }}"
    headers: "{{ ansistrano_download_headers | default(omit) }}"
    timeout: 600
