---
- name: ANSISTRANO | download | download hook
  get_url:
    url: "{{ ansistrano_hook_get_url }}"
    dest: "{{ ansistrano_hook_archived_file }}"
    force_basic_auth: "{{ ansistrano_download_force_basic_auth | default(omit) }}"
    headers: "{{ ansistrano_callback_headers | default(omit) }}"
