---
- name: ANSISTRANO | download_unarchive | Create hook folder
  file:
    state: directory
    path: "{{ ansistrano_hook_path.stdout }}"

- name: ANSISTRANO | download_unarchive | Set hook archived file variable
  set_fact:
    ansistrano_hook_archived_file: "{{ ansistrano_hook_path.stdout }}/{{ ansistrano_hook_get_url | basename }}"

- include_tasks: download.yml

- include_tasks: unarchive.yml
