---
- name: ANSISTRANO | download_unarchive | Create config folder
  file:
    state: directory
    path: "{{ ansistrano_config_path.stdout }}"

- name: ANSISTRANO | download_unarchive | Set config archived file variable
  set_fact:
    ansistrano_config_archived_file: "{{ ansistrano_config_path.stdout }}/configs.tar.gz"

- include_tasks: download.yml

- include_tasks: unarchive.yml
