---
- name: ANSISTRANO | download | download config
  get_url:
    url: "{{ ansistrano_config_get_url }}?host_ip={{ ansible_default_ipv4.address }}"
    dest: "{{ ansistrano_config_archived_file }}"
    force_basic_auth: "{{ ansistrano_download_force_basic_auth | default(omit) }}"
    headers: "{{ ansistrano_callback_headers | default(omit) }}"
